/* Main.c file generated by New Project wizard
 *
 * Created:   ?? ?? 18 2017
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg52.h>
#include <stdio.h>
#include "adc0809.h"

#define uchar unsigned char
#define LCD P1
sbit START = P2^2;
sbit EOC = P2^0;
sbit OE = P2^1;

sbit RS = P2^6;
sbit RW = P2^5;
sbit E = P2^7;
uchar tmp;
uchar i = 0;
void busy(){
   for(i=0;i<200;i++);
   /*uchar status = 0; 
   RS = 0;
    RW = 1;
   do{
      E = 1;
   for(i=0;i<200;i++);
    status = LCD;
   E = 0;
   }while(status&0x080 == 0x80);
   */
   
}

void lcd_writeCMD(uchar cmd){
   RS = 0;
   RW = 0;
   busy();
   E = 1;
   LCD = cmd;
   for(i=0;i<5;i++);
   E = 0;
   for(i=0;i<5;i++);
}

void lcd_writeData(uchar d){
   RS = 1;
   RW = 0;
   busy();
   E = 1;
   LCD = d;
   for(i=0;i<5;i++);
   E = 0;
   for(i=0;i<5;i++);
}
void init_LCD(){
   lcd_writeCMD(0x38);
   lcd_writeCMD(0x0c);
   lcd_writeCMD(0x06);
   lcd_writeCMD(0x01);
}

void start_ADC(){
    START = 0;
    START = 1;
    START = 0;
}
void adc0809(void)
 { 
   //init_interrupt();
   init_LCD();
    
   while(1){
      start_ADC();
      while(EOC == 0);
	    OE = 1;
   for(i=0;i<20;i++);
   tmp = P0;
   OE=0;
   tmp = (i*5*100)/256;
   lcd_writeCMD(0x80);
   lcd_writeData('0'+tmp/100);
   lcd_writeCMD(0x81);
   lcd_writeData('.');
   lcd_writeCMD(0x82);
   lcd_writeData('0'+(tmp/10)%10);
   lcd_writeCMD(0x83);
   lcd_writeData(('0'+tmp%10));
   } 
 }
