/* Main.c file generated by New Project wizard
 *
 * Created:   ?? ?? 15 2017
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>
#define uchar unsigned char
#define uint unsigned int
sbit RS = P2^0;
sbit RW = P2^1;
sbit E = P2^2;

uchar code tab[] = {"123456789"};

void writeCMD(uchar cmd){
	uchar m;
	RW = 0;//0???,1???
	RS = 0;//0????,1????
	P1 = cmd;
	for(m-0;m<=2;m++);
	E = 1;//????
	for(m-0;m<=2;m++);
	E = 0;//????
}

void writeData(uchar c){
	uchar m;
	RW = 0;
	RS = 1;
	P1 = c;
	for(m-0;m<=2;m++);
	E = 1;//????
	for(m-0;m<=2;m++);
	E = 0;//????
}

//?????,?????????,???
void init(){
	RW = 0;//??????
	E = 0;//????
	writeCMD(0):
	writeCMD(0x0c);
	writeCMD(0x06);
	writeCMD(0x01);
}

void show_char(uchar row,uchar column,uchar c){
	uchar m;
	writeCMD(0x80+row*0x40+column);//???,?????
	for(m=0;m<252;m++);
	writeData(c);
	
}
void main(void)
 { 
	 uchar i;
	 uint j;
	 init();
	 for(i=0;i<=9;i++){
		show_char(0,tab[i]);
		show_char(1,tab[i]); 
	 }
	 while(1);
 }