/* Main.c file generated by New Project wizard
 *
 * Created:   ?? ?? 12 2017
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg52.h>
#include <stdio.h>
#include "step_motor.h"
void main(){
	step_motor();
}