/* Main.c file generated by New Project wizard
 *
 * Created:   ?? ?? 12 2017
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>
#include "adc0809.h"
void main(){
	adc0809();
}